apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: drone-server
  name: drone-server
spec:
  type: NodePort
  ports:
  - name: "30800"
    port: 30800
    targetPort: 8000
    nodePort: 30800
  selector:
    io.kompose.service: drone-server
status:
  loadBalancer: {}
