apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: drone-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drone-server
    spec:
      containers:
      - env:
        - name: DRONE_OPEN
          value: "true"
        - name: DRONE_DEBUG
          value: "true"
        - name: DRONE_GOGS
          value: "true"
        - name: DRONE_GOGS_URL
          value: http://gogs:30080
        - name: DRONE_GOGS_PRIVATE_MODE
          value: "true"
        - name: DRONE_GOGS_SKIP_VERIFY
          value: "true"
        - name: DRONE_SECRET
          value: "dronedafahao"
        image: drone/drone:0.5.0
        name: drone-server
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/drone/
          name: drone-server-claim0
      restartPolicy: Always
      volumes:
      - name: drone-server-claim0
        persistentVolumeClaim:
          claimName: drone-server-claim0
status: {}
