apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: drone-agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drone-agent
    spec:
      containers:
      - args:
        - agent
        env:
        - name: DRONE_SERVER
          value: ws://drone-server:30800/ws/broker
        - name: DRONE_DEBUG
          value: "true"
        - name: DRONE_SECRET
          value: "dronedafahao"
        image: drone/drone:0.5.0
        name: drone-agent
        resources: {}
        volumeMounts:
          # Enables Docker in Docker
          - mountPath: /var/run/docker.sock
            name: docker-socket
      restartPolicy: Always
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
status: {}
