apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gogs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gogs
    spec:
      containers:
      - env:
        - name: Domain
          value: 0.0.0.0
        - name: SSH_PORT
          value: "10022"
        image: gogs/gogs:0.11.4
        name: gogs
        ports:
        - containerPort: 22
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: gogs-claim0
      restartPolicy: Always
      volumes:
      - name: gogs-claim0
        persistentVolumeClaim:
          claimName: gogs-claim0
status: {}
