apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gogs
  name: gogs
spec:
  type: NodePort
  ports:
  - name: "30022"
    port: 30022
    targetPort: 22
    nodePort: 30022
  - name: "30080"
    port: 30080
    targetPort: 3000
    nodePort: 30080
  selector:
    io.kompose.service: gogs
status:
  loadBalancer: {}
