version: '2'

services:
  app:
    image: gogs/gogs:0.11.4
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./data:/data
    restart: always
    links:
        - mysql:mysql
    environment:
      - Domain=0.0.0.0
      - SSH_PORT=10022

  mysql:
    image: mysql:5.7.13
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gogsdafahao
      - MYSQL_DATABASE=gogs
